--!native
--!optimize 2
--!nocheck
--!nolint
--#selene: allow(unused_variable, global_usage)
-- Client generated by Zap v0.6.28 (https://github.com/red-blox/zap)
local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
if RunService:IsServer() then
	error("Cannot use the client module on the server!")
end

if not _G.__ZAP then
	_G.__ZAP = { ["ZAP"] = {} }
elseif not _G.__ZAP["ZAP"] then
	_G.__ZAP["ZAP"] = {}
elseif _G.__ZAP["ZAP"]["AVALOG"] ~= nil then
	error(`There is already an instance of Zap with the same remote_scope of AVALOG, remote_folder of ZAP and the version of {_G.__ZAP["ZAP"]["AVALOG"]}. Change the remote_scope or remote_folder option of both Zap instances`)
end

_G.__ZAP["ZAP"]["AVALOG"] = "0.6.28"

local outgoing_buff: buffer
local outgoing_used: number
local outgoing_size: number
local outgoing_inst: { Instance }
local outgoing_apos: number
local outgoing_ids: { number }

local incoming_buff: buffer
local incoming_read: number
local incoming_inst: { Instance }
local incoming_ipos: number
local incoming_ids: { number }

-- thanks to https://dom.rojo.space/binary.html#cframe
local CFrameSpecialCases = {
	CFrame.Angles(0, 0, 0),
	CFrame.Angles(math.rad(90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(180)),
	CFrame.Angles(math.rad(-90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(90)),
	CFrame.Angles(0, math.rad(90), math.rad(90)),
	CFrame.Angles(0, 0, math.rad(90)),
	CFrame.Angles(0, math.rad(-90), math.rad(90)),
	CFrame.Angles(math.rad(-90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(-90), 0),
	CFrame.Angles(math.rad(90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(90), math.rad(180)),
	CFrame.Angles(0, math.rad(-90), math.rad(180)),
	CFrame.Angles(0, math.rad(180), math.rad(0)),
	CFrame.Angles(math.rad(-90), math.rad(-180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(180)),
	CFrame.Angles(math.rad(90), math.rad(180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(-90)),
	CFrame.Angles(0, math.rad(-90), math.rad(-90)),
	CFrame.Angles(0, math.rad(-180), math.rad(-90)),
	CFrame.Angles(0, math.rad(90), math.rad(-90)),
	CFrame.Angles(math.rad(90), math.rad(90), 0),
	CFrame.Angles(0, math.rad(90), 0),
	CFrame.Angles(math.rad(-90), math.rad(90), 0),
}

local function alloc(len: number)
	if outgoing_used + len > outgoing_size then
		while outgoing_used + len > outgoing_size do
			outgoing_size = outgoing_size * 2
		end

		local new_buff = buffer.create(outgoing_size)
		buffer.copy(new_buff, 0, outgoing_buff, 0, outgoing_used)

		outgoing_buff = new_buff
	end

	outgoing_apos = outgoing_used
	outgoing_used = outgoing_used + len

	return outgoing_apos
end

local function read(len: number)
	local pos = incoming_read
	incoming_read = incoming_read + len

	return pos
end

local function save()
	return {
		buff = outgoing_buff,
		used = outgoing_used,
		size = outgoing_size,
		inst = outgoing_inst,
		outgoing_ids = outgoing_ids,
		incoming_ids = incoming_ids,
	}
end

local function load(data: {
	buff: buffer,
	used: number,
	size: number,
	inst: { Instance },
	outgoing_ids: { number },
	incoming_ids: { number },
})
	outgoing_buff = data.buff
	outgoing_used = data.used
	outgoing_size = data.size
	outgoing_inst = data.inst
	outgoing_ids = data.outgoing_ids
	incoming_ids = data.incoming_ids
end

local function load_empty()
	outgoing_buff = buffer.create(64)
	outgoing_used = 0
	outgoing_size = 64
	outgoing_inst = {}
	outgoing_ids = {}
	incoming_ids = {}
end

load_empty()

local types = {}

local polling_queues_reliable = {}
local polling_queues_unreliable = {}
if not RunService:IsRunning() then
	local noop = function() end
	return table.freeze({
		SendEvents = noop,
		UpdateAvatar = table.freeze({
			Fire = noop
		}),
		GetFeaturedItems = table.freeze({
			Call = noop
		}),
		FeaturedItemsReset = table.freeze({
			SetCallback = noop
		}),
		BulkPurchaseAvatarItems = table.freeze({
			Fire = noop
		}),
	}) :: Events
end
local remotes = ReplicatedStorage:WaitForChild("ZAP")

local reliable = remotes:WaitForChild("AVALOG_RELIABLE")
assert(reliable:IsA("RemoteEvent"), "Expected AVALOG_RELIABLE to be a RemoteEvent")

export type CatalogItem = ({
	["AssetId"]: (number),
	["Name"]: (string),
	["Type"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
	["AssetType"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
})
export type AvatarItem = ({
	["Id"]: (number),
	["Type"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
	["AssetType"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
	["Name"]: (string),
})
export type BulkPurchaseAvatarItem = ({
	["Id"]: (string),
	["Type"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
})
export type FeaturedData = ({
	["Items"]: ({ ({
		["TransactionHash"]: (string),
		["Bid"]: (number),
		["StartTime"]: (number),
		["EndTime"]: (number),
		["Power"]: (number),
		["Id"]: (number),
		["ItemType"]: ({
			["EnumType"]: (string),
			["Value"]: (number),
		}),
	}) }),
	["Creators"]: ({ ({
		["TransactionHash"]: (string),
		["Bid"]: (number),
		["StartTime"]: (number),
		["EndTime"]: (number),
		["Power"]: (number),
		["Id"]: (number),
		["CreatorType"]: ({
			["EnumType"]: (string),
			["Value"]: (number),
		}),
	}) }),
})
export type FeaturedItem = ({
	["TransactionHash"]: (string),
	["Bid"]: (number),
	["StartTime"]: (number),
	["EndTime"]: (number),
	["Power"]: (number),
	["Id"]: (number),
	["ItemType"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
})
export type HumanoidDescriberData = ({
	["Accessories"]: ({ ({
		["AssetId"]: (number),
		["AccessoryType"]: ({
			["EnumType"]: (string),
			["Value"]: (number),
		}),
		["Order"]: ((number)?),
		["Puffiness"]: ((number)?),
		["IsLayered"]: ((boolean)?),
		["Position"]: ((Vector3)?),
		["Rotation"]: ((Vector3)?),
		["Scale"]: ((Vector3)?),
	}) }),
	["Emotes"]: ({ [(string)]: ({ (number) }) }),
	["EquippedEmotes"]: ({ ({
		["Name"]: (string),
		["Slot"]: (number),
	}) }),
	["Face"]: (number),
	["Scale"]: ({
		["BodyType"]: (number),
		["Depth"]: (number),
		["Head"]: (number),
		["Height"]: (number),
		["Proportion"]: (number),
		["Width"]: (number),
	}),
	["Animations"]: ({
		["Walk"]: (number),
		["Run"]: (number),
		["Fall"]: (number),
		["Climb"]: (number),
		["Swim"]: (number),
		["Idle"]: (number),
		["Mood"]: (number),
		["Jump"]: (number),
	}),
	["BodyParts"]: ({
		["Head"]: (number),
		["Torso"]: (number),
		["LeftArm"]: (number),
		["RightArm"]: (number),
		["LeftLeg"]: (number),
		["RightLeg"]: (number),
	}),
	["BodyPartColors"]: ({
		["Head"]: (Color3),
		["Torso"]: (Color3),
		["LeftArm"]: (Color3),
		["RightArm"]: (Color3),
		["LeftLeg"]: (Color3),
		["RightLeg"]: (Color3),
	}),
	["Clothing"]: ({
		["Shirt"]: (number),
		["TShirt"]: (number),
		["Pants"]: (number),
	}),
})
export type FeaturedCreator = ({
	["TransactionHash"]: (string),
	["Bid"]: (number),
	["StartTime"]: (number),
	["EndTime"]: (number),
	["Power"]: (number),
	["Id"]: (number),
	["CreatorType"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
})
export type AccessorySpec = ({
	["AssetId"]: (number),
	["AccessoryType"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
	["Order"]: ((number)?),
	["Puffiness"]: ((number)?),
	["IsLayered"]: ((boolean)?),
	["Position"]: ((Vector3)?),
	["Rotation"]: ((Vector3)?),
	["Scale"]: ((Vector3)?),
})
export type EquippedEmote = ({
	["Name"]: (string),
	["Slot"]: (number),
})
export type SerEnumItem = ({
	["EnumType"]: (string),
	["Value"]: (number),
})

local function SendEvents()
	if outgoing_used ~= 0 then
		local buff = buffer.create(outgoing_used)
		buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)

		reliable:FireServer(buff, outgoing_inst)

		outgoing_buff = buffer.create(64)
		outgoing_used = 0
		outgoing_size = 64
		table.clear(outgoing_inst)
	end
end

RunService.Heartbeat:Connect(SendEvents)

local reliable_events = table.create(2)
local reliable_event_queue: { [number]: { any } } = table.create(2)
local function_call_id = 0
reliable_event_queue[0] = 0
reliable_event_queue[1] = table.create(255)
reliable.OnClientEvent:Connect(function(buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local len = buffer.len(buff)
	while incoming_read < len do
		local id = buffer.readu8(buff, read(1))
		if id == 0 then -- FeaturedItemsReset
			local value
			if reliable_events[0] then
				task.spawn(reliable_events[0], value)
			else
				reliable_event_queue[0] += 1
				if reliable_event_queue[0] > 16 then
					warn(`[ZAP] {reliable_event_queue[0]} events in queue for FeaturedItemsReset. Did you forget to attach a listener?`)
				end
			end
		elseif id == 1 then -- GetFeaturedItems
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			local bool_1 = buffer.readu8(incoming_buff, read(1))
			if bit32.btest(bool_1, 0b0000000000000001) then
				local len_1 = buffer.readu16(incoming_buff, read(2))
				value = table.create(len_1)
				for i_1 = 1, len_1 do
					local val_1
					val_1 = {  }
					local len_2 = buffer.readu16(incoming_buff, read(2))
					val_1["TransactionHash"] = buffer.readstring(incoming_buff, read(len_2), len_2)
					val_1["Bid"] = buffer.readf64(incoming_buff, read(8))
					val_1["StartTime"] = buffer.readf64(incoming_buff, read(8))
					val_1["EndTime"] = buffer.readf64(incoming_buff, read(8))
					val_1["Power"] = buffer.readf64(incoming_buff, read(8))
					val_1["Id"] = buffer.readf64(incoming_buff, read(8))
					val_1["ItemType"] = {  }
					local len_3 = buffer.readu16(incoming_buff, read(2))
					val_1["ItemType"]["EnumType"] = buffer.readstring(incoming_buff, read(len_3), len_3)
					val_1["ItemType"]["Value"] = buffer.readu16(incoming_buff, read(2))
					value[i_1] = val_1
				end
			else
				value = nil
			end
			local thread = reliable_event_queue[1][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[1][call_id] = nil
		else
			error("Unknown event id")
		end
	end
end)
table.freeze(polling_queues_reliable)
table.freeze(polling_queues_unreliable)

local returns = {
	SendEvents = SendEvents,
	UpdateAvatar = {
		Fire = function(Value: ({
			["Accessories"]: ({ ({
				["AssetId"]: (number),
				["AccessoryType"]: ({
					["EnumType"]: (string),
					["Value"]: (number),
				}),
				["Order"]: ((number)?),
				["Puffiness"]: ((number)?),
				["IsLayered"]: ((boolean)?),
				["Position"]: ((Vector3)?),
				["Rotation"]: ((Vector3)?),
				["Scale"]: ((Vector3)?),
			}) }),
			["Emotes"]: ({ [(string)]: ({ (number) }) }),
			["EquippedEmotes"]: ({ ({
				["Name"]: (string),
				["Slot"]: (number),
			}) }),
			["Face"]: (number),
			["Scale"]: ({
				["BodyType"]: (number),
				["Depth"]: (number),
				["Head"]: (number),
				["Height"]: (number),
				["Proportion"]: (number),
				["Width"]: (number),
			}),
			["Animations"]: ({
				["Walk"]: (number),
				["Run"]: (number),
				["Fall"]: (number),
				["Climb"]: (number),
				["Swim"]: (number),
				["Idle"]: (number),
				["Mood"]: (number),
				["Jump"]: (number),
			}),
			["BodyParts"]: ({
				["Head"]: (number),
				["Torso"]: (number),
				["LeftArm"]: (number),
				["RightArm"]: (number),
				["LeftLeg"]: (number),
				["RightLeg"]: (number),
			}),
			["BodyPartColors"]: ({
				["Head"]: (Color3),
				["Torso"]: (Color3),
				["LeftArm"]: (Color3),
				["RightArm"]: (Color3),
				["LeftLeg"]: (Color3),
				["RightLeg"]: (Color3),
			}),
			["Clothing"]: ({
				["Shirt"]: (number),
				["TShirt"]: (number),
				["Pants"]: (number),
			}),
		}))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			local bool_3 = 0
			local bool_3_pos_1 = alloc(1)
			local len_4 = #Value["Accessories"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_4)
			for i_2 = 1, len_4 do
				local bool_2 = 0
				local bool_2_pos_1 = alloc(1)
				local val_2 = Value["Accessories"][i_2]
				alloc(8)
				buffer.writef64(outgoing_buff, outgoing_apos, val_2["AssetId"])
				local len_5 = #val_2["AccessoryType"]["EnumType"]
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_5)
				alloc(len_5)
				buffer.writestring(outgoing_buff, outgoing_apos, val_2["AccessoryType"]["EnumType"], len_5)
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, val_2["AccessoryType"]["Value"])
				if val_2["Order"] ~= nil then
					bool_2 = bit32.bor(bool_2, 0b0000000000000001)
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, val_2["Order"])
				end
				if val_2["Puffiness"] ~= nil then
					bool_2 = bit32.bor(bool_2, 0b0000000000000010)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_2["Puffiness"])
				end
				if val_2["IsLayered"] ~= nil then
					bool_2 = bit32.bor(bool_2, 0b0000000000000100)
					if val_2["IsLayered"] then
						bool_2 = bit32.bor(bool_2, 0b0000000000001000)
					end
				end
				if val_2["Position"] ~= nil then
					bool_2 = bit32.bor(bool_2, 0b0000000000010000)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_2["Position"].X)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_2["Position"].Y)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_2["Position"].Z)
				end
				if val_2["Rotation"] ~= nil then
					bool_2 = bit32.bor(bool_2, 0b0000000000100000)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_2["Rotation"].X)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_2["Rotation"].Y)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_2["Rotation"].Z)
				end
				if val_2["Scale"] ~= nil then
					bool_2 = bit32.bor(bool_2, 0b0000000001000000)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_2["Scale"].X)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_2["Scale"].Y)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_2["Scale"].Z)
				end
				buffer.writeu8(outgoing_buff, bool_2_pos_1, bool_2)
			end
			local len_pos_1
			local len_6 = 0
			for k_1, v_1 in Value["Emotes"] do
				if len_6 == 0 then
					len_pos_1 = alloc(2)
				end
				len_6 = len_6 + 1
				local len_7 = #k_1
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_7)
				alloc(len_7)
				buffer.writestring(outgoing_buff, outgoing_apos, k_1, len_7)
				local len_8 = #v_1
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_8)
				for i_3 = 1, len_8 do
					local val_3 = v_1[i_3]
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, val_3)
				end
			end
			if len_pos_1 then
				buffer.writeu16(outgoing_buff, len_pos_1, len_6 - 1)
			else
				bool_3 = bit32.bor(bool_3, 0b0000000000000001)
			end
			local len_9 = #Value["EquippedEmotes"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_9)
			for i_4 = 1, len_9 do
				local val_4 = Value["EquippedEmotes"][i_4]
				local len_10 = #val_4["Name"]
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_10)
				alloc(len_10)
				buffer.writestring(outgoing_buff, outgoing_apos, val_4["Name"], len_10)
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, val_4["Slot"])
			end
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Face"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Scale"]["BodyType"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Scale"]["Depth"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Scale"]["Head"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Scale"]["Height"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Scale"]["Proportion"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Scale"]["Width"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Walk"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Run"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Fall"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Climb"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Swim"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Idle"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Mood"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Jump"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["BodyParts"]["Head"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["BodyParts"]["Torso"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["BodyParts"]["LeftArm"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["BodyParts"]["RightArm"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["BodyParts"]["LeftLeg"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["BodyParts"]["RightLeg"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["Head"].R * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["Head"].G * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["Head"].B * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["Torso"].R * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["Torso"].G * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["Torso"].B * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["LeftArm"].R * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["LeftArm"].G * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["LeftArm"].B * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["RightArm"].R * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["RightArm"].G * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["RightArm"].B * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["LeftLeg"].R * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["LeftLeg"].G * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["LeftLeg"].B * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["RightLeg"].R * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["RightLeg"].G * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["RightLeg"].B * 255)
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Clothing"]["Shirt"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Clothing"]["TShirt"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Clothing"]["Pants"])
			buffer.writeu8(outgoing_buff, bool_3_pos_1, bool_3)
		end,
	},
	GetFeaturedItems = {
		Call = function(Value: (number), Value2: (number)): ((({ ({
			["TransactionHash"]: (string),
			["Bid"]: (number),
			["StartTime"]: (number),
			["EndTime"]: (number),
			["Power"]: (number),
			["Id"]: (number),
			["ItemType"]: ({
				["EnumType"]: (string),
				["Value"]: (number),
			}),
		}) })?))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[1][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value)
			alloc(4)
			buffer.writeu32(outgoing_buff, outgoing_apos, Value2)
			reliable_event_queue[1][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
	FeaturedItemsReset = {
		SetCallback = function(Callback: () -> ()): () -> ()
			reliable_events[0] = Callback
			for _ = 1, reliable_event_queue[0] do
				task.spawn(Callback)
			end
			reliable_event_queue[0] = 0
			return function()
				reliable_events[0] = nil
			end
		end,
	},
	BulkPurchaseAvatarItems = {
		Fire = function(Value: ({ ({
			["Id"]: (string),
			["Type"]: ({
				["EnumType"]: (string),
				["Value"]: (number),
			}),
		}) }))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local len_11 = #Value
			assert(len_11 >= 1, "value is less than 1!")
			assert(len_11 <= 20, "value is more than 20!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_11 - 1)
			for i_5 = 1, len_11 do
				local val_5 = Value[i_5]
				local len_12 = #val_5["Id"]
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_12)
				alloc(len_12)
				buffer.writestring(outgoing_buff, outgoing_apos, val_5["Id"], len_12)
				local len_13 = #val_5["Type"]["EnumType"]
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_13)
				alloc(len_13)
				buffer.writestring(outgoing_buff, outgoing_apos, val_5["Type"]["EnumType"], len_13)
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, val_5["Type"]["Value"])
			end
		end,
	},
}
type Events = typeof(returns)
return returns
