--!native
--!optimize 2
--!nocheck
--!nolint
--#selene: allow(unused_variable, global_usage)
-- Client generated by Zap v0.6.28 (https://github.com/red-blox/zap)
local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
if RunService:IsServer() then
	error("Cannot use the client module on the server!")
end

if not _G.__ZAP then
	_G.__ZAP = { ["ZAP"] = {} }
elseif not _G.__ZAP["ZAP"] then
	_G.__ZAP["ZAP"] = {}
elseif _G.__ZAP["ZAP"]["AVALOG"] ~= nil then
	error(`There is already an instance of Zap with the same remote_scope of AVALOG, remote_folder of ZAP and the version of {_G.__ZAP["ZAP"]["AVALOG"]}. Change the remote_scope or remote_folder option of both Zap instances`)
end

_G.__ZAP["ZAP"]["AVALOG"] = "0.6.28"

local outgoing_buff: buffer
local outgoing_used: number
local outgoing_size: number
local outgoing_inst: { Instance }
local outgoing_apos: number
local outgoing_ids: { number }

local incoming_buff: buffer
local incoming_read: number
local incoming_inst: { Instance }
local incoming_ipos: number
local incoming_ids: { number }

-- thanks to https://dom.rojo.space/binary.html#cframe
local CFrameSpecialCases = {
	CFrame.Angles(0, 0, 0),
	CFrame.Angles(math.rad(90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(180)),
	CFrame.Angles(math.rad(-90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(90)),
	CFrame.Angles(0, math.rad(90), math.rad(90)),
	CFrame.Angles(0, 0, math.rad(90)),
	CFrame.Angles(0, math.rad(-90), math.rad(90)),
	CFrame.Angles(math.rad(-90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(-90), 0),
	CFrame.Angles(math.rad(90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(90), math.rad(180)),
	CFrame.Angles(0, math.rad(-90), math.rad(180)),
	CFrame.Angles(0, math.rad(180), math.rad(0)),
	CFrame.Angles(math.rad(-90), math.rad(-180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(180)),
	CFrame.Angles(math.rad(90), math.rad(180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(-90)),
	CFrame.Angles(0, math.rad(-90), math.rad(-90)),
	CFrame.Angles(0, math.rad(-180), math.rad(-90)),
	CFrame.Angles(0, math.rad(90), math.rad(-90)),
	CFrame.Angles(math.rad(90), math.rad(90), 0),
	CFrame.Angles(0, math.rad(90), 0),
	CFrame.Angles(math.rad(-90), math.rad(90), 0),
}

local function alloc(len: number)
	if outgoing_used + len > outgoing_size then
		while outgoing_used + len > outgoing_size do
			outgoing_size = outgoing_size * 2
		end

		local new_buff = buffer.create(outgoing_size)
		buffer.copy(new_buff, 0, outgoing_buff, 0, outgoing_used)

		outgoing_buff = new_buff
	end

	outgoing_apos = outgoing_used
	outgoing_used = outgoing_used + len

	return outgoing_apos
end

local function read(len: number)
	local pos = incoming_read
	incoming_read = incoming_read + len

	return pos
end

local function save()
	return {
		buff = outgoing_buff,
		used = outgoing_used,
		size = outgoing_size,
		inst = outgoing_inst,
		outgoing_ids = outgoing_ids,
		incoming_ids = incoming_ids,
	}
end

local function load(data: {
	buff: buffer,
	used: number,
	size: number,
	inst: { Instance },
	outgoing_ids: { number },
	incoming_ids: { number },
})
	outgoing_buff = data.buff
	outgoing_used = data.used
	outgoing_size = data.size
	outgoing_inst = data.inst
	outgoing_ids = data.outgoing_ids
	incoming_ids = data.incoming_ids
end

local function load_empty()
	outgoing_buff = buffer.create(64)
	outgoing_used = 0
	outgoing_size = 64
	outgoing_inst = {}
	outgoing_ids = {}
	incoming_ids = {}
end

load_empty()

local types = {}

local polling_queues_reliable = {}
local polling_queues_unreliable = {}
if not RunService:IsRunning() then
	local noop = function() end
	return table.freeze({
		SendEvents = noop,
		UpdateAvatar = table.freeze({
			Fire = noop
		}),
		RecordPurchase = table.freeze({
			Fire = noop
		}),
		RecordMenuToggle = table.freeze({
			Fire = noop
		}),
		GetCloudConfig = table.freeze({
			Call = noop
		}),
		CloudConfigReset = table.freeze({
			SetCallback = noop
		}),
		BulkPurchaseAvatarItems = table.freeze({
			Fire = noop
		}),
	}) :: Events
end
local remotes = ReplicatedStorage:WaitForChild("ZAP")

local reliable = remotes:WaitForChild("AVALOG_RELIABLE")
assert(reliable:IsA("RemoteEvent"), "Expected AVALOG_RELIABLE to be a RemoteEvent")

export type ItemType = ("Asset" | "Bundle")
export type AvatarItem = ({
	["Id"]: (number),
	["Type"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
	["AssetType"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
	["Name"]: (string),
})
export type HumanoidDescriberData = ({
	["Accessories"]: ({ ({
		["AssetId"]: (number),
		["AccessoryType"]: ({
			["EnumType"]: (string),
			["Value"]: (number),
		}),
		["Order"]: ((number)?),
		["Puffiness"]: ((number)?),
		["IsLayered"]: ((boolean)?),
		["Position"]: ((Vector3)?),
		["Rotation"]: ((Vector3)?),
		["Scale"]: ((Vector3)?),
	}) }),
	["Emotes"]: ({ [(string)]: ({ (number) }) }),
	["EquippedEmotes"]: ({ ({
		["Name"]: (string),
		["Slot"]: (number),
	}) }),
	["Face"]: (number),
	["Scale"]: ({
		["BodyType"]: (number),
		["Depth"]: (number),
		["Head"]: (number),
		["Height"]: (number),
		["Proportion"]: (number),
		["Width"]: (number),
	}),
	["Animations"]: ({
		["Walk"]: (number),
		["Run"]: (number),
		["Fall"]: (number),
		["Climb"]: (number),
		["Swim"]: (number),
		["Idle"]: (number),
		["Mood"]: (number),
		["Jump"]: (number),
	}),
	["BodyParts"]: ({
		["Head"]: (number),
		["Torso"]: (number),
		["LeftArm"]: (number),
		["RightArm"]: (number),
		["LeftLeg"]: (number),
		["RightLeg"]: (number),
	}),
	["BodyPartColors"]: ({
		["Head"]: (Color3),
		["Torso"]: (Color3),
		["LeftArm"]: (Color3),
		["RightArm"]: (Color3),
		["LeftLeg"]: (Color3),
		["RightLeg"]: (Color3),
	}),
	["Clothing"]: ({
		["Shirt"]: (number),
		["TShirt"]: (number),
		["Pants"]: (number),
	}),
})
export type AccessorySpec = ({
	["AssetId"]: (number),
	["AccessoryType"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
	["Order"]: ((number)?),
	["Puffiness"]: ((number)?),
	["IsLayered"]: ((boolean)?),
	["Position"]: ((Vector3)?),
	["Rotation"]: ((Vector3)?),
	["Scale"]: ((Vector3)?),
})
export type SerEnumItem = ({
	["EnumType"]: (string),
	["Value"]: (number),
})
export type Item = ({
	["itemId"]: (string),
	["itemType"]: ("Asset" | "Bundle"),
	["tintColor"]: ((string)?),
})
export type PromotedItem = ({
	["itemId"]: (string),
	["itemType"]: ("Asset" | "Bundle"),
	["tintColor"]: ((string)?),
	["promotionId"]: (string),
	["bid"]: (number),
	["startTime"]: (number),
	["endTime"]: (number),
})
export type BulkPurchaseAvatarItem = ({
	["Id"]: (string),
	["Type"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
})
export type EquippedEmote = ({
	["Name"]: (string),
	["Slot"]: (number),
})
export type CatalogItem = ({
	["AssetId"]: (number),
	["Name"]: (string),
	["Type"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
	["AssetType"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
})
export type CloudConfig = ({
	["latestVersion"]: (string),
	["featuredItems"]: ({ ({
		["itemId"]: (string),
		["itemType"]: ("Asset" | "Bundle"),
		["tintColor"]: ((string)?),
	}) }),
	["pinnedItems"]: ({ ({
		["itemId"]: (string),
		["itemType"]: ("Asset" | "Bundle"),
		["tintColor"]: ((string)?),
	}) }),
	["promotedItems"]: ({ ({
		["itemId"]: (string),
		["itemType"]: ("Asset" | "Bundle"),
		["tintColor"]: ((string)?),
		["promotionId"]: (string),
		["bid"]: (number),
		["startTime"]: (number),
		["endTime"]: (number),
	}) }),
})

local function SendEvents()
	if outgoing_used ~= 0 then
		local buff = buffer.create(outgoing_used)
		buffer.copy(buff, 0, outgoing_buff, 0, outgoing_used)

		reliable:FireServer(buff, outgoing_inst)

		outgoing_buff = buffer.create(64)
		outgoing_used = 0
		outgoing_size = 64
		table.clear(outgoing_inst)
	end
end

RunService.Heartbeat:Connect(SendEvents)

local reliable_events = table.create(2)
local reliable_event_queue: { [number]: { any } } = table.create(2)
local function_call_id = 0
reliable_event_queue[0] = 0
reliable_event_queue[1] = table.create(255)
reliable.OnClientEvent:Connect(function(buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local len = buffer.len(buff)
	while incoming_read < len do
		local id = buffer.readu8(buff, read(1))
		if id == 0 then -- CloudConfigReset
			local value
			if reliable_events[0] then
				task.spawn(reliable_events[0], value)
			else
				reliable_event_queue[0] += 1
				if reliable_event_queue[0] > 16 then
					warn(`[ZAP] {reliable_event_queue[0]} events in queue for CloudConfigReset. Did you forget to attach a listener?`)
				end
			end
		elseif id == 1 then -- GetCloudConfig
			local call_id = buffer.readu8(incoming_buff, read(1))
			local value
			local bool_1 = buffer.readu8(incoming_buff, read(1))
			if bit32.btest(bool_1, 0b0000000000000001) then
				value = {  }
				local len_1 = buffer.readu16(incoming_buff, read(2))
				value["latestVersion"] = buffer.readstring(incoming_buff, read(len_1), len_1)
				local len_2 = buffer.readu16(incoming_buff, read(2))
				value["featuredItems"] = table.create(len_2)
				for i_1 = 1, len_2 do
					local bool_2 = buffer.readu8(incoming_buff, read(1))
					local val_1
					val_1 = {  }
					local len_3 = buffer.readu16(incoming_buff, read(2))
					val_1["itemId"] = buffer.readstring(incoming_buff, read(len_3), len_3)
					if bit32.btest(bool_2, 0b0000000000000001) then
						val_1["itemType"] = "Asset"
					else
						val_1["itemType"] = "Bundle"
					end
					if bit32.btest(bool_2, 0b0000000000000010) then
						local len_4 = buffer.readu16(incoming_buff, read(2))
						val_1["tintColor"] = buffer.readstring(incoming_buff, read(len_4), len_4)
					else
						val_1["tintColor"] = nil
					end
					value["featuredItems"][i_1] = val_1
				end
				local len_5 = buffer.readu16(incoming_buff, read(2))
				value["pinnedItems"] = table.create(len_5)
				for i_2 = 1, len_5 do
					local bool_3 = buffer.readu8(incoming_buff, read(1))
					local val_2
					val_2 = {  }
					local len_6 = buffer.readu16(incoming_buff, read(2))
					val_2["itemId"] = buffer.readstring(incoming_buff, read(len_6), len_6)
					if bit32.btest(bool_3, 0b0000000000000001) then
						val_2["itemType"] = "Asset"
					else
						val_2["itemType"] = "Bundle"
					end
					if bit32.btest(bool_3, 0b0000000000000010) then
						local len_7 = buffer.readu16(incoming_buff, read(2))
						val_2["tintColor"] = buffer.readstring(incoming_buff, read(len_7), len_7)
					else
						val_2["tintColor"] = nil
					end
					value["pinnedItems"][i_2] = val_2
				end
				local len_8 = buffer.readu16(incoming_buff, read(2))
				value["promotedItems"] = table.create(len_8)
				for i_3 = 1, len_8 do
					local bool_4 = buffer.readu8(incoming_buff, read(1))
					local val_3
					val_3 = {  }
					local len_9 = buffer.readu16(incoming_buff, read(2))
					val_3["itemId"] = buffer.readstring(incoming_buff, read(len_9), len_9)
					if bit32.btest(bool_4, 0b0000000000000001) then
						val_3["itemType"] = "Asset"
					else
						val_3["itemType"] = "Bundle"
					end
					if bit32.btest(bool_4, 0b0000000000000010) then
						local len_10 = buffer.readu16(incoming_buff, read(2))
						val_3["tintColor"] = buffer.readstring(incoming_buff, read(len_10), len_10)
					else
						val_3["tintColor"] = nil
					end
					local len_11 = buffer.readu16(incoming_buff, read(2))
					val_3["promotionId"] = buffer.readstring(incoming_buff, read(len_11), len_11)
					val_3["bid"] = buffer.readf32(incoming_buff, read(4))
					val_3["startTime"] = buffer.readf32(incoming_buff, read(4))
					val_3["endTime"] = buffer.readf32(incoming_buff, read(4))
					value["promotedItems"][i_3] = val_3
				end
			else
				value = nil
			end
			local thread = reliable_event_queue[1][call_id]
			-- When using actors it's possible for multiple Zap clients to exist, but only one called the Zap remote function.
			if thread then
				task.spawn(thread, value)
			end
			reliable_event_queue[1][call_id] = nil
		else
			error("Unknown event id")
		end
	end
end)
table.freeze(polling_queues_reliable)
table.freeze(polling_queues_unreliable)

local returns = {
	SendEvents = SendEvents,
	UpdateAvatar = {
		Fire = function(Value: ({
			["Accessories"]: ({ ({
				["AssetId"]: (number),
				["AccessoryType"]: ({
					["EnumType"]: (string),
					["Value"]: (number),
				}),
				["Order"]: ((number)?),
				["Puffiness"]: ((number)?),
				["IsLayered"]: ((boolean)?),
				["Position"]: ((Vector3)?),
				["Rotation"]: ((Vector3)?),
				["Scale"]: ((Vector3)?),
			}) }),
			["Emotes"]: ({ [(string)]: ({ (number) }) }),
			["EquippedEmotes"]: ({ ({
				["Name"]: (string),
				["Slot"]: (number),
			}) }),
			["Face"]: (number),
			["Scale"]: ({
				["BodyType"]: (number),
				["Depth"]: (number),
				["Head"]: (number),
				["Height"]: (number),
				["Proportion"]: (number),
				["Width"]: (number),
			}),
			["Animations"]: ({
				["Walk"]: (number),
				["Run"]: (number),
				["Fall"]: (number),
				["Climb"]: (number),
				["Swim"]: (number),
				["Idle"]: (number),
				["Mood"]: (number),
				["Jump"]: (number),
			}),
			["BodyParts"]: ({
				["Head"]: (number),
				["Torso"]: (number),
				["LeftArm"]: (number),
				["RightArm"]: (number),
				["LeftLeg"]: (number),
				["RightLeg"]: (number),
			}),
			["BodyPartColors"]: ({
				["Head"]: (Color3),
				["Torso"]: (Color3),
				["LeftArm"]: (Color3),
				["RightArm"]: (Color3),
				["LeftLeg"]: (Color3),
				["RightLeg"]: (Color3),
			}),
			["Clothing"]: ({
				["Shirt"]: (number),
				["TShirt"]: (number),
				["Pants"]: (number),
			}),
		}))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 1)
			local bool_6 = 0
			local bool_6_pos_1 = alloc(1)
			local len_12 = #Value["Accessories"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_12)
			for i_4 = 1, len_12 do
				local bool_5 = 0
				local bool_5_pos_1 = alloc(1)
				local val_4 = Value["Accessories"][i_4]
				alloc(8)
				buffer.writef64(outgoing_buff, outgoing_apos, val_4["AssetId"])
				local len_13 = #val_4["AccessoryType"]["EnumType"]
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_13)
				alloc(len_13)
				buffer.writestring(outgoing_buff, outgoing_apos, val_4["AccessoryType"]["EnumType"], len_13)
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, val_4["AccessoryType"]["Value"])
				if val_4["Order"] ~= nil then
					bool_5 = bit32.bor(bool_5, 0b0000000000000001)
					alloc(2)
					buffer.writeu16(outgoing_buff, outgoing_apos, val_4["Order"])
				end
				if val_4["Puffiness"] ~= nil then
					bool_5 = bit32.bor(bool_5, 0b0000000000000010)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_4["Puffiness"])
				end
				if val_4["IsLayered"] ~= nil then
					bool_5 = bit32.bor(bool_5, 0b0000000000000100)
					if val_4["IsLayered"] then
						bool_5 = bit32.bor(bool_5, 0b0000000000001000)
					end
				end
				if val_4["Position"] ~= nil then
					bool_5 = bit32.bor(bool_5, 0b0000000000010000)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_4["Position"].X)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_4["Position"].Y)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_4["Position"].Z)
				end
				if val_4["Rotation"] ~= nil then
					bool_5 = bit32.bor(bool_5, 0b0000000000100000)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_4["Rotation"].X)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_4["Rotation"].Y)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_4["Rotation"].Z)
				end
				if val_4["Scale"] ~= nil then
					bool_5 = bit32.bor(bool_5, 0b0000000001000000)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_4["Scale"].X)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_4["Scale"].Y)
					alloc(4)
					buffer.writef32(outgoing_buff, outgoing_apos, val_4["Scale"].Z)
				end
				buffer.writeu8(outgoing_buff, bool_5_pos_1, bool_5)
			end
			local len_pos_1
			local len_14 = 0
			for k_1, v_1 in Value["Emotes"] do
				if len_14 == 0 then
					len_pos_1 = alloc(2)
				end
				len_14 = len_14 + 1
				local len_15 = #k_1
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_15)
				alloc(len_15)
				buffer.writestring(outgoing_buff, outgoing_apos, k_1, len_15)
				local len_16 = #v_1
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_16)
				for i_5 = 1, len_16 do
					local val_5 = v_1[i_5]
					alloc(8)
					buffer.writef64(outgoing_buff, outgoing_apos, val_5)
				end
			end
			if len_pos_1 then
				buffer.writeu16(outgoing_buff, len_pos_1, len_14 - 1)
			else
				bool_6 = bit32.bor(bool_6, 0b0000000000000001)
			end
			local len_17 = #Value["EquippedEmotes"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_17)
			for i_6 = 1, len_17 do
				local val_6 = Value["EquippedEmotes"][i_6]
				local len_18 = #val_6["Name"]
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_18)
				alloc(len_18)
				buffer.writestring(outgoing_buff, outgoing_apos, val_6["Name"], len_18)
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, val_6["Slot"])
			end
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Face"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Scale"]["BodyType"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Scale"]["Depth"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Scale"]["Head"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Scale"]["Height"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Scale"]["Proportion"])
			alloc(4)
			buffer.writef32(outgoing_buff, outgoing_apos, Value["Scale"]["Width"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Walk"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Run"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Fall"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Climb"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Swim"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Idle"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Mood"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Animations"]["Jump"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["BodyParts"]["Head"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["BodyParts"]["Torso"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["BodyParts"]["LeftArm"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["BodyParts"]["RightArm"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["BodyParts"]["LeftLeg"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["BodyParts"]["RightLeg"])
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["Head"].R * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["Head"].G * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["Head"].B * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["Torso"].R * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["Torso"].G * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["Torso"].B * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["LeftArm"].R * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["LeftArm"].G * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["LeftArm"].B * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["RightArm"].R * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["RightArm"].G * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["RightArm"].B * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["LeftLeg"].R * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["LeftLeg"].G * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["LeftLeg"].B * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["RightLeg"].R * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["RightLeg"].G * 255)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, Value["BodyPartColors"]["RightLeg"].B * 255)
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Clothing"]["Shirt"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Clothing"]["TShirt"])
			alloc(8)
			buffer.writef64(outgoing_buff, outgoing_apos, Value["Clothing"]["Pants"])
			buffer.writeu8(outgoing_buff, bool_6_pos_1, bool_6)
		end,
	},
	RecordPurchase = {
		Fire = function(Item: ({
			["itemId"]: (string),
			["itemType"]: ("Asset" | "Bundle"),
			["tintColor"]: ((string)?),
		}))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 2)
			local bool_7 = 0
			local bool_7_pos_1 = alloc(1)
			local len_19 = #Item["itemId"]
			alloc(2)
			buffer.writeu16(outgoing_buff, outgoing_apos, len_19)
			alloc(len_19)
			buffer.writestring(outgoing_buff, outgoing_apos, Item["itemId"], len_19)
			if Item["itemType"] == "Asset" then
				bool_7 = bit32.bor(bool_7, 0b0000000000000001)
			elseif Item["itemType"] == "Bundle" then
				local _
			else
				error("Invalid enumerator")
			end
			if Item["tintColor"] ~= nil then
				bool_7 = bit32.bor(bool_7, 0b0000000000000010)
				local len_20 = #Item["tintColor"]
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_20)
				alloc(len_20)
				buffer.writestring(outgoing_buff, outgoing_apos, Item["tintColor"], len_20)
			end
			buffer.writeu8(outgoing_buff, bool_7_pos_1, bool_7)
		end,
	},
	RecordMenuToggle = {
		Fire = function(Open: (boolean))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 3)
			local bool_8 = 0
			local bool_8_pos_1 = alloc(1)
			if Open then
				bool_8 = bit32.bor(bool_8, 0b0000000000000001)
			end
			buffer.writeu8(outgoing_buff, bool_8_pos_1, bool_8)
		end,
	},
	GetCloudConfig = {
		Call = function(): ((({
			["latestVersion"]: (string),
			["featuredItems"]: ({ ({
				["itemId"]: (string),
				["itemType"]: ("Asset" | "Bundle"),
				["tintColor"]: ((string)?),
			}) }),
			["pinnedItems"]: ({ ({
				["itemId"]: (string),
				["itemType"]: ("Asset" | "Bundle"),
				["tintColor"]: ((string)?),
			}) }),
			["promotedItems"]: ({ ({
				["itemId"]: (string),
				["itemType"]: ("Asset" | "Bundle"),
				["tintColor"]: ((string)?),
				["promotionId"]: (string),
				["bid"]: (number),
				["startTime"]: (number),
				["endTime"]: (number),
			}) }),
		})?))
			function_call_id += 1
			function_call_id %= 256
			if reliable_event_queue[1][function_call_id] then
				function_call_id -= 1
				error("Zap has more than 256 calls awaiting a response, and therefore this packet has been dropped")
			end
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 4)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, function_call_id)
			reliable_event_queue[1][function_call_id] = coroutine.running()
			return coroutine.yield()
		end,
	},
	CloudConfigReset = {
		SetCallback = function(Callback: () -> ()): () -> ()
			reliable_events[0] = Callback
			for _ = 1, reliable_event_queue[0] do
				task.spawn(Callback)
			end
			reliable_event_queue[0] = 0
			return function()
				reliable_events[0] = nil
			end
		end,
	},
	BulkPurchaseAvatarItems = {
		Fire = function(Value: ({ ({
			["Id"]: (string),
			["Type"]: ({
				["EnumType"]: (string),
				["Value"]: (number),
			}),
		}) }))
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local len_21 = #Value
			assert(len_21 >= 1, "value is less than 1!")
			assert(len_21 <= 20, "value is more than 20!")
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, len_21 - 1)
			for i_7 = 1, len_21 do
				local val_7 = Value[i_7]
				local len_22 = #val_7["Id"]
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_22)
				alloc(len_22)
				buffer.writestring(outgoing_buff, outgoing_apos, val_7["Id"], len_22)
				local len_23 = #val_7["Type"]["EnumType"]
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, len_23)
				alloc(len_23)
				buffer.writestring(outgoing_buff, outgoing_apos, val_7["Type"]["EnumType"], len_23)
				alloc(2)
				buffer.writeu16(outgoing_buff, outgoing_apos, val_7["Type"]["Value"])
			end
		end,
	},
}
type Events = typeof(returns)
return returns
