--!native
--!optimize 2
--!nocheck
--!nolint
--#selene: allow(unused_variable, global_usage)
-- Server generated by Zap v0.6.28 (https://github.com/red-blox/zap)
local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")

if RunService:IsClient() then
	error("Cannot use the server module on the client!")
end

if not _G.__ZAP then
	_G.__ZAP = { ["ZAP"] = {} }
elseif not _G.__ZAP["ZAP"] then
	_G.__ZAP["ZAP"] = {}
elseif _G.__ZAP["ZAP"]["AVALOG"] ~= nil then
	error(`There is already an instance of Zap with the same remote_scope of AVALOG, remote_folder of ZAP and the version of {_G.__ZAP["ZAP"]["AVALOG"]}. Change the remote_scope or remote_folder option of both Zap instances`)
end

_G.__ZAP["ZAP"]["AVALOG"] = "0.6.28"

local outgoing_buff: buffer
local outgoing_used: number
local outgoing_size: number
local outgoing_inst: { Instance }
local outgoing_apos: number
local outgoing_ids: { number }

local incoming_buff: buffer
local incoming_read: number
local incoming_inst: { Instance }
local incoming_ipos: number
local incoming_ids: { number }

-- thanks to https://dom.rojo.space/binary.html#cframe
local CFrameSpecialCases = {
	CFrame.Angles(0, 0, 0),
	CFrame.Angles(math.rad(90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(180)),
	CFrame.Angles(math.rad(-90), 0, 0),
	CFrame.Angles(0, math.rad(180), math.rad(90)),
	CFrame.Angles(0, math.rad(90), math.rad(90)),
	CFrame.Angles(0, 0, math.rad(90)),
	CFrame.Angles(0, math.rad(-90), math.rad(90)),
	CFrame.Angles(math.rad(-90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(-90), 0),
	CFrame.Angles(math.rad(90), math.rad(-90), 0),
	CFrame.Angles(0, math.rad(90), math.rad(180)),
	CFrame.Angles(0, math.rad(-90), math.rad(180)),
	CFrame.Angles(0, math.rad(180), math.rad(0)),
	CFrame.Angles(math.rad(-90), math.rad(-180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(180)),
	CFrame.Angles(math.rad(90), math.rad(180), math.rad(0)),
	CFrame.Angles(0, math.rad(0), math.rad(-90)),
	CFrame.Angles(0, math.rad(-90), math.rad(-90)),
	CFrame.Angles(0, math.rad(-180), math.rad(-90)),
	CFrame.Angles(0, math.rad(90), math.rad(-90)),
	CFrame.Angles(math.rad(90), math.rad(90), 0),
	CFrame.Angles(0, math.rad(90), 0),
	CFrame.Angles(math.rad(-90), math.rad(90), 0),
}

local function alloc(len: number)
	if outgoing_used + len > outgoing_size then
		while outgoing_used + len > outgoing_size do
			outgoing_size = outgoing_size * 2
		end

		local new_buff = buffer.create(outgoing_size)
		buffer.copy(new_buff, 0, outgoing_buff, 0, outgoing_used)

		outgoing_buff = new_buff
	end

	outgoing_apos = outgoing_used
	outgoing_used = outgoing_used + len

	return outgoing_apos
end

local function read(len: number)
	local pos = incoming_read
	incoming_read = incoming_read + len

	return pos
end

local function save()
	return {
		buff = outgoing_buff,
		used = outgoing_used,
		size = outgoing_size,
		inst = outgoing_inst,
		outgoing_ids = outgoing_ids,
		incoming_ids = incoming_ids,
	}
end

local function load(data: {
	buff: buffer,
	used: number,
	size: number,
	inst: { Instance },
	outgoing_ids: { number },
	incoming_ids: { number },
})
	outgoing_buff = data.buff
	outgoing_used = data.used
	outgoing_size = data.size
	outgoing_inst = data.inst
	outgoing_ids = data.outgoing_ids
	incoming_ids = data.incoming_ids
end

local function load_empty()
	outgoing_buff = buffer.create(64)
	outgoing_used = 0
	outgoing_size = 64
	outgoing_inst = {}
	outgoing_ids = {}
	incoming_ids = {}
end

load_empty()

local types = {}

local polling_queues_reliable = {}
local polling_queues_unreliable = {}
if not RunService:IsRunning() then
	local noop = function() end
	return table.freeze({
		SendEvents = noop,
		UpdateAvatar = table.freeze({
			SetCallback = noop
		}),
		RecordPurchase = table.freeze({
			SetCallback = noop
		}),
		RecordMenuToggle = table.freeze({
			SetCallback = noop
		}),
		GetCloudConfig = table.freeze({
			SetCallback = noop
		}),
		CloudConfigReset = table.freeze({
			Fire = noop,
			FireAll = noop,
			FireExcept = noop,
			FireList = noop,
			FireSet = noop
		}),
		BulkPurchaseAvatarItems = table.freeze({
			SetCallback = noop
		}),
	}) :: Events
end

local remotes = ReplicatedStorage:FindFirstChild("ZAP")
if remotes == nil then
	remotes = Instance.new("Folder")
	remotes.Name = "ZAP"
	remotes.Parent = ReplicatedStorage
end

local reliable = remotes:FindFirstChild("AVALOG_RELIABLE")
if reliable == nil then
	reliable = Instance.new("RemoteEvent")
	reliable.Name = "AVALOG_RELIABLE"
	reliable.Parent = remotes
end

local player_map = {}

local function load_player(player: Player)
	if player_map[player] then
		load(player_map[player])
	else
		load_empty()
	end
end

Players.PlayerRemoving:Connect(function(player)
	player_map[player] = nil
end)
export type ItemType = ("Asset" | "Bundle")
export type AvatarItem = ({
	["Id"]: (number),
	["Type"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
	["AssetType"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
	["Name"]: (string),
})
export type BulkPurchaseAvatarItem = ({
	["Id"]: (string),
	["Type"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
})
export type AccessorySpec = ({
	["AssetId"]: (number),
	["AccessoryType"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
	["Order"]: ((number)?),
	["Puffiness"]: ((number)?),
	["IsLayered"]: ((boolean)?),
	["Position"]: ((Vector3)?),
	["Rotation"]: ((Vector3)?),
	["Scale"]: ((Vector3)?),
})
export type EquippedEmote = ({
	["Name"]: (string),
	["Slot"]: (number),
})
export type HumanoidDescriberData = ({
	["Accessories"]: ({ ({
		["AssetId"]: (number),
		["AccessoryType"]: ({
			["EnumType"]: (string),
			["Value"]: (number),
		}),
		["Order"]: ((number)?),
		["Puffiness"]: ((number)?),
		["IsLayered"]: ((boolean)?),
		["Position"]: ((Vector3)?),
		["Rotation"]: ((Vector3)?),
		["Scale"]: ((Vector3)?),
	}) }),
	["Emotes"]: ({ [(string)]: ({ (number) }) }),
	["EquippedEmotes"]: ({ ({
		["Name"]: (string),
		["Slot"]: (number),
	}) }),
	["Face"]: (number),
	["Scale"]: ({
		["BodyType"]: (number),
		["Depth"]: (number),
		["Head"]: (number),
		["Height"]: (number),
		["Proportion"]: (number),
		["Width"]: (number),
	}),
	["Animations"]: ({
		["Walk"]: (number),
		["Run"]: (number),
		["Fall"]: (number),
		["Climb"]: (number),
		["Swim"]: (number),
		["Idle"]: (number),
		["Mood"]: (number),
		["Jump"]: (number),
	}),
	["BodyParts"]: ({
		["Head"]: (number),
		["Torso"]: (number),
		["LeftArm"]: (number),
		["RightArm"]: (number),
		["LeftLeg"]: (number),
		["RightLeg"]: (number),
	}),
	["BodyPartColors"]: ({
		["Head"]: (Color3),
		["Torso"]: (Color3),
		["LeftArm"]: (Color3),
		["RightArm"]: (Color3),
		["LeftLeg"]: (Color3),
		["RightLeg"]: (Color3),
	}),
	["Clothing"]: ({
		["Shirt"]: (number),
		["TShirt"]: (number),
		["Pants"]: (number),
	}),
})
export type CloudConfig = ({
	["latestVersion"]: (string),
	["featuredItems"]: ({ ({
		["itemId"]: (string),
		["itemType"]: ("Asset" | "Bundle"),
		["tintColor"]: ((string)?),
	}) }),
	["pinnedItems"]: ({ ({
		["itemId"]: (string),
		["itemType"]: ("Asset" | "Bundle"),
		["tintColor"]: ((string)?),
	}) }),
	["promotedItems"]: ({ ({
		["itemId"]: (string),
		["itemType"]: ("Asset" | "Bundle"),
		["tintColor"]: ((string)?),
		["promotionId"]: (string),
		["bid"]: (number),
		["startTime"]: (number),
		["endTime"]: (number),
	}) }),
	["cosmeticItems"]: ({ ({
		["itemId"]: (string),
		["itemType"]: ("Asset" | "Bundle"),
		["tintColor"]: ((string)?),
	}) }),
})
export type SerEnumItem = ({
	["EnumType"]: (string),
	["Value"]: (number),
})
export type CatalogItem = ({
	["AssetId"]: (number),
	["Name"]: (string),
	["Type"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
	["AssetType"]: ({
		["EnumType"]: (string),
		["Value"]: (number),
	}),
})
export type PromotedItem = ({
	["itemId"]: (string),
	["itemType"]: ("Asset" | "Bundle"),
	["tintColor"]: ((string)?),
	["promotionId"]: (string),
	["bid"]: (number),
	["startTime"]: (number),
	["endTime"]: (number),
})
export type Item = ({
	["itemId"]: (string),
	["itemType"]: ("Asset" | "Bundle"),
	["tintColor"]: ((string)?),
})

local function SendEvents()
	for player, outgoing in player_map do
		if outgoing.used > 0 then
			local buff = buffer.create(outgoing.used)
			buffer.copy(buff, 0, outgoing.buff, 0, outgoing.used)

			reliable:FireClient(player, buff, outgoing.inst)

			outgoing.buff = buffer.create(64)
			outgoing.used = 0
			outgoing.size = 64
			table.clear(outgoing.inst)
		end
	end
end

RunService.Heartbeat:Connect(SendEvents)

local reliable_events = table.create(5)
reliable.OnServerEvent:Connect(function(player, buff, inst)
	incoming_buff = buff
	incoming_inst = inst
	incoming_read = 0
	incoming_ipos = 0
	local len = buffer.len(buff)
	while incoming_read < len do
		local id = buffer.readu8(buff, read(1))
		if id == 1 then -- UpdateAvatar
			local value
			local bool_2 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			local len_1 = buffer.readu16(incoming_buff, read(2))
			value["Accessories"] = table.create(len_1)
			for i_1 = 1, len_1 do
				local bool_1 = buffer.readu8(incoming_buff, read(1))
				local val_1
				val_1 = {  }
				val_1["AssetId"] = buffer.readf64(incoming_buff, read(8))
				val_1["AccessoryType"] = {  }
				local len_2 = buffer.readu16(incoming_buff, read(2))
				val_1["AccessoryType"]["EnumType"] = buffer.readstring(incoming_buff, read(len_2), len_2)
				val_1["AccessoryType"]["Value"] = buffer.readu16(incoming_buff, read(2))
				if bit32.btest(bool_1, 0b0000000000000001) then
					val_1["Order"] = buffer.readu16(incoming_buff, read(2))
				else
					val_1["Order"] = nil
				end
				if bit32.btest(bool_1, 0b0000000000000010) then
					val_1["Puffiness"] = buffer.readf32(incoming_buff, read(4))
				else
					val_1["Puffiness"] = nil
				end
				if bit32.btest(bool_1, 0b0000000000000100) then
					val_1["IsLayered"] = bit32.btest(bool_1, 0b0000000000001000)
				else
					val_1["IsLayered"] = nil
				end
				if bit32.btest(bool_1, 0b0000000000010000) then
					val_1["Position"] = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
				else
					val_1["Position"] = nil
				end
				if bit32.btest(bool_1, 0b0000000000100000) then
					val_1["Rotation"] = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
				else
					val_1["Rotation"] = nil
				end
				if bit32.btest(bool_1, 0b0000000001000000) then
					val_1["Scale"] = Vector3.new(buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)), buffer.readf32(incoming_buff, read(4)))
				else
					val_1["Scale"] = nil
				end
				value["Accessories"][i_1] = val_1
			end
			value["Emotes"] = {  }
			if not bit32.btest(bool_2, 0b0000000000000001) then
				for _ = 1, buffer.readu16(incoming_buff, read(2)) + 1 do
					local key_1
					local val_2
					local len_3 = buffer.readu16(incoming_buff, read(2))
					key_1 = buffer.readstring(incoming_buff, read(len_3), len_3)
					local len_4 = buffer.readu16(incoming_buff, read(2))
					val_2 = table.create(len_4)
					for i_2 = 1, len_4 do
						local val_3
						val_3 = buffer.readf64(incoming_buff, read(8))
						val_2[i_2] = val_3
					end
					value["Emotes"][key_1] = val_2
				end
			end
			local len_5 = buffer.readu16(incoming_buff, read(2))
			value["EquippedEmotes"] = table.create(len_5)
			for i_3 = 1, len_5 do
				local val_4
				val_4 = {  }
				local len_6 = buffer.readu16(incoming_buff, read(2))
				val_4["Name"] = buffer.readstring(incoming_buff, read(len_6), len_6)
				val_4["Slot"] = buffer.readu16(incoming_buff, read(2))
				value["EquippedEmotes"][i_3] = val_4
			end
			value["Face"] = buffer.readf64(incoming_buff, read(8))
			value["Scale"] = {  }
			value["Scale"]["BodyType"] = buffer.readf32(incoming_buff, read(4))
			value["Scale"]["Depth"] = buffer.readf32(incoming_buff, read(4))
			value["Scale"]["Head"] = buffer.readf32(incoming_buff, read(4))
			value["Scale"]["Height"] = buffer.readf32(incoming_buff, read(4))
			value["Scale"]["Proportion"] = buffer.readf32(incoming_buff, read(4))
			value["Scale"]["Width"] = buffer.readf32(incoming_buff, read(4))
			value["Animations"] = {  }
			value["Animations"]["Walk"] = buffer.readf64(incoming_buff, read(8))
			value["Animations"]["Run"] = buffer.readf64(incoming_buff, read(8))
			value["Animations"]["Fall"] = buffer.readf64(incoming_buff, read(8))
			value["Animations"]["Climb"] = buffer.readf64(incoming_buff, read(8))
			value["Animations"]["Swim"] = buffer.readf64(incoming_buff, read(8))
			value["Animations"]["Idle"] = buffer.readf64(incoming_buff, read(8))
			value["Animations"]["Mood"] = buffer.readf64(incoming_buff, read(8))
			value["Animations"]["Jump"] = buffer.readf64(incoming_buff, read(8))
			value["BodyParts"] = {  }
			value["BodyParts"]["Head"] = buffer.readf64(incoming_buff, read(8))
			value["BodyParts"]["Torso"] = buffer.readf64(incoming_buff, read(8))
			value["BodyParts"]["LeftArm"] = buffer.readf64(incoming_buff, read(8))
			value["BodyParts"]["RightArm"] = buffer.readf64(incoming_buff, read(8))
			value["BodyParts"]["LeftLeg"] = buffer.readf64(incoming_buff, read(8))
			value["BodyParts"]["RightLeg"] = buffer.readf64(incoming_buff, read(8))
			value["BodyPartColors"] = {  }
			value["BodyPartColors"]["Head"] = Color3.fromRGB(buffer.readu8(incoming_buff, read(1)), buffer.readu8(incoming_buff, read(1)), buffer.readu8(incoming_buff, read(1)))
			value["BodyPartColors"]["Torso"] = Color3.fromRGB(buffer.readu8(incoming_buff, read(1)), buffer.readu8(incoming_buff, read(1)), buffer.readu8(incoming_buff, read(1)))
			value["BodyPartColors"]["LeftArm"] = Color3.fromRGB(buffer.readu8(incoming_buff, read(1)), buffer.readu8(incoming_buff, read(1)), buffer.readu8(incoming_buff, read(1)))
			value["BodyPartColors"]["RightArm"] = Color3.fromRGB(buffer.readu8(incoming_buff, read(1)), buffer.readu8(incoming_buff, read(1)), buffer.readu8(incoming_buff, read(1)))
			value["BodyPartColors"]["LeftLeg"] = Color3.fromRGB(buffer.readu8(incoming_buff, read(1)), buffer.readu8(incoming_buff, read(1)), buffer.readu8(incoming_buff, read(1)))
			value["BodyPartColors"]["RightLeg"] = Color3.fromRGB(buffer.readu8(incoming_buff, read(1)), buffer.readu8(incoming_buff, read(1)), buffer.readu8(incoming_buff, read(1)))
			value["Clothing"] = {  }
			value["Clothing"]["Shirt"] = buffer.readf64(incoming_buff, read(8))
			value["Clothing"]["TShirt"] = buffer.readf64(incoming_buff, read(8))
			value["Clothing"]["Pants"] = buffer.readf64(incoming_buff, read(8))
			if reliable_events[1] then
				task.spawn(reliable_events[1], player, value)
			end
		elseif id == 2 then -- RecordPurchase
			local value
			local bool_3 = buffer.readu8(incoming_buff, read(1))
			value = {  }
			local len_7 = buffer.readu16(incoming_buff, read(2))
			value["itemId"] = buffer.readstring(incoming_buff, read(len_7), len_7)
			if bit32.btest(bool_3, 0b0000000000000001) then
				value["itemType"] = "Asset"
			else
				value["itemType"] = "Bundle"
			end
			if bit32.btest(bool_3, 0b0000000000000010) then
				local len_8 = buffer.readu16(incoming_buff, read(2))
				value["tintColor"] = buffer.readstring(incoming_buff, read(len_8), len_8)
			else
				value["tintColor"] = nil
			end
			if reliable_events[2] then
				task.spawn(reliable_events[2], player, value)
			end
		elseif id == 3 then -- RecordMenuToggle
			local value
			local bool_4 = buffer.readu8(incoming_buff, read(1))
			value = bit32.btest(bool_4, 0b0000000000000001)
			if reliable_events[3] then
				task.spawn(reliable_events[3], player, value)
			end
		elseif id == 0 then -- BulkPurchaseAvatarItems
			local value
			local len_9 = buffer.readu8(incoming_buff, read(1)) + 1
			assert(len_9 >= 1, "value is less than 1!")
			assert(len_9 <= 20, "value is more than 20!")
			value = table.create(len_9)
			for i_4 = 1, len_9 do
				local val_5
				val_5 = {  }
				local len_10 = buffer.readu16(incoming_buff, read(2))
				val_5["Id"] = buffer.readstring(incoming_buff, read(len_10), len_10)
				val_5["Type"] = {  }
				local len_11 = buffer.readu16(incoming_buff, read(2))
				val_5["Type"]["EnumType"] = buffer.readstring(incoming_buff, read(len_11), len_11)
				val_5["Type"]["Value"] = buffer.readu16(incoming_buff, read(2))
				value[i_4] = val_5
			end
			if reliable_events[0] then
				task.spawn(reliable_events[0], player, value)
			end
		elseif id == 4 then -- GetCloudConfig
			local call_id = buffer.readu8(buff, read(1))
			local value
			if reliable_events[4] then
				task.spawn(function(player_2, call_id_2, value_1)
					local ret_1 = reliable_events[4](player_2, value_1)
					load_player(player_2)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, 1)
					alloc(1)
					buffer.writeu8(outgoing_buff, outgoing_apos, call_id_2)
					local bool_5 = 0
					local bool_5_pos_1 = alloc(1)
					if ret_1 ~= nil then
						bool_5 = bit32.bor(bool_5, 0b0000000000000001)
						local len_12 = #ret_1["latestVersion"]
						alloc(2)
						buffer.writeu16(outgoing_buff, outgoing_apos, len_12)
						alloc(len_12)
						buffer.writestring(outgoing_buff, outgoing_apos, ret_1["latestVersion"], len_12)
						local len_13 = #ret_1["featuredItems"]
						alloc(2)
						buffer.writeu16(outgoing_buff, outgoing_apos, len_13)
						for i_5 = 1, len_13 do
							local bool_6 = 0
							local bool_6_pos_1 = alloc(1)
							local val_6 = ret_1["featuredItems"][i_5]
							local len_14 = #val_6["itemId"]
							alloc(2)
							buffer.writeu16(outgoing_buff, outgoing_apos, len_14)
							alloc(len_14)
							buffer.writestring(outgoing_buff, outgoing_apos, val_6["itemId"], len_14)
							if val_6["itemType"] == "Asset" then
								bool_6 = bit32.bor(bool_6, 0b0000000000000001)
							elseif val_6["itemType"] == "Bundle" then
								local _
							else
								error("Invalid enumerator")
							end
							if val_6["tintColor"] ~= nil then
								bool_6 = bit32.bor(bool_6, 0b0000000000000010)
								local len_15 = #val_6["tintColor"]
								alloc(2)
								buffer.writeu16(outgoing_buff, outgoing_apos, len_15)
								alloc(len_15)
								buffer.writestring(outgoing_buff, outgoing_apos, val_6["tintColor"], len_15)
							end
							buffer.writeu8(outgoing_buff, bool_6_pos_1, bool_6)
						end
						local len_16 = #ret_1["pinnedItems"]
						alloc(2)
						buffer.writeu16(outgoing_buff, outgoing_apos, len_16)
						for i_6 = 1, len_16 do
							local bool_7 = 0
							local bool_7_pos_1 = alloc(1)
							local val_7 = ret_1["pinnedItems"][i_6]
							local len_17 = #val_7["itemId"]
							alloc(2)
							buffer.writeu16(outgoing_buff, outgoing_apos, len_17)
							alloc(len_17)
							buffer.writestring(outgoing_buff, outgoing_apos, val_7["itemId"], len_17)
							if val_7["itemType"] == "Asset" then
								bool_7 = bit32.bor(bool_7, 0b0000000000000001)
							elseif val_7["itemType"] == "Bundle" then
								local _
							else
								error("Invalid enumerator")
							end
							if val_7["tintColor"] ~= nil then
								bool_7 = bit32.bor(bool_7, 0b0000000000000010)
								local len_18 = #val_7["tintColor"]
								alloc(2)
								buffer.writeu16(outgoing_buff, outgoing_apos, len_18)
								alloc(len_18)
								buffer.writestring(outgoing_buff, outgoing_apos, val_7["tintColor"], len_18)
							end
							buffer.writeu8(outgoing_buff, bool_7_pos_1, bool_7)
						end
						local len_19 = #ret_1["promotedItems"]
						alloc(2)
						buffer.writeu16(outgoing_buff, outgoing_apos, len_19)
						for i_7 = 1, len_19 do
							local bool_8 = 0
							local bool_8_pos_1 = alloc(1)
							local val_8 = ret_1["promotedItems"][i_7]
							local len_20 = #val_8["itemId"]
							alloc(2)
							buffer.writeu16(outgoing_buff, outgoing_apos, len_20)
							alloc(len_20)
							buffer.writestring(outgoing_buff, outgoing_apos, val_8["itemId"], len_20)
							if val_8["itemType"] == "Asset" then
								bool_8 = bit32.bor(bool_8, 0b0000000000000001)
							elseif val_8["itemType"] == "Bundle" then
								local _
							else
								error("Invalid enumerator")
							end
							if val_8["tintColor"] ~= nil then
								bool_8 = bit32.bor(bool_8, 0b0000000000000010)
								local len_21 = #val_8["tintColor"]
								alloc(2)
								buffer.writeu16(outgoing_buff, outgoing_apos, len_21)
								alloc(len_21)
								buffer.writestring(outgoing_buff, outgoing_apos, val_8["tintColor"], len_21)
							end
							local len_22 = #val_8["promotionId"]
							alloc(2)
							buffer.writeu16(outgoing_buff, outgoing_apos, len_22)
							alloc(len_22)
							buffer.writestring(outgoing_buff, outgoing_apos, val_8["promotionId"], len_22)
							alloc(4)
							buffer.writef32(outgoing_buff, outgoing_apos, val_8["bid"])
							alloc(4)
							buffer.writef32(outgoing_buff, outgoing_apos, val_8["startTime"])
							alloc(4)
							buffer.writef32(outgoing_buff, outgoing_apos, val_8["endTime"])
							buffer.writeu8(outgoing_buff, bool_8_pos_1, bool_8)
						end
						local len_23 = #ret_1["cosmeticItems"]
						alloc(2)
						buffer.writeu16(outgoing_buff, outgoing_apos, len_23)
						for i_8 = 1, len_23 do
							local bool_9 = 0
							local bool_9_pos_1 = alloc(1)
							local val_9 = ret_1["cosmeticItems"][i_8]
							local len_24 = #val_9["itemId"]
							alloc(2)
							buffer.writeu16(outgoing_buff, outgoing_apos, len_24)
							alloc(len_24)
							buffer.writestring(outgoing_buff, outgoing_apos, val_9["itemId"], len_24)
							if val_9["itemType"] == "Asset" then
								bool_9 = bit32.bor(bool_9, 0b0000000000000001)
							elseif val_9["itemType"] == "Bundle" then
								local _
							else
								error("Invalid enumerator")
							end
							if val_9["tintColor"] ~= nil then
								bool_9 = bit32.bor(bool_9, 0b0000000000000010)
								local len_25 = #val_9["tintColor"]
								alloc(2)
								buffer.writeu16(outgoing_buff, outgoing_apos, len_25)
								alloc(len_25)
								buffer.writestring(outgoing_buff, outgoing_apos, val_9["tintColor"], len_25)
							end
							buffer.writeu8(outgoing_buff, bool_9_pos_1, bool_9)
						end
					end
					buffer.writeu8(outgoing_buff, bool_5_pos_1, bool_5)
					player_map[player_2] = save()
				end, player, call_id, value)
			end
		else
			error("Unknown event id")
		end
	end
end)
table.freeze(polling_queues_reliable)
table.freeze(polling_queues_unreliable)

local returns = {
	SendEvents = SendEvents,
	UpdateAvatar = {
		SetCallback = function(Callback: (Player: Player, Value: ({
			["Accessories"]: ({ ({
				["AssetId"]: (number),
				["AccessoryType"]: ({
					["EnumType"]: (string),
					["Value"]: (number),
				}),
				["Order"]: ((number)?),
				["Puffiness"]: ((number)?),
				["IsLayered"]: ((boolean)?),
				["Position"]: ((Vector3)?),
				["Rotation"]: ((Vector3)?),
				["Scale"]: ((Vector3)?),
			}) }),
			["Emotes"]: ({ [(string)]: ({ (number) }) }),
			["EquippedEmotes"]: ({ ({
				["Name"]: (string),
				["Slot"]: (number),
			}) }),
			["Face"]: (number),
			["Scale"]: ({
				["BodyType"]: (number),
				["Depth"]: (number),
				["Head"]: (number),
				["Height"]: (number),
				["Proportion"]: (number),
				["Width"]: (number),
			}),
			["Animations"]: ({
				["Walk"]: (number),
				["Run"]: (number),
				["Fall"]: (number),
				["Climb"]: (number),
				["Swim"]: (number),
				["Idle"]: (number),
				["Mood"]: (number),
				["Jump"]: (number),
			}),
			["BodyParts"]: ({
				["Head"]: (number),
				["Torso"]: (number),
				["LeftArm"]: (number),
				["RightArm"]: (number),
				["LeftLeg"]: (number),
				["RightLeg"]: (number),
			}),
			["BodyPartColors"]: ({
				["Head"]: (Color3),
				["Torso"]: (Color3),
				["LeftArm"]: (Color3),
				["RightArm"]: (Color3),
				["LeftLeg"]: (Color3),
				["RightLeg"]: (Color3),
			}),
			["Clothing"]: ({
				["Shirt"]: (number),
				["TShirt"]: (number),
				["Pants"]: (number),
			}),
		})) -> ()): () -> ()
			reliable_events[1] = Callback
			return function()
				reliable_events[1] = nil
			end
		end,
	},
	RecordPurchase = {
		SetCallback = function(Callback: (Player: Player, Item: ({
			["itemId"]: (string),
			["itemType"]: ("Asset" | "Bundle"),
			["tintColor"]: ((string)?),
		})) -> ()): () -> ()
			reliable_events[2] = Callback
			return function()
				reliable_events[2] = nil
			end
		end,
	},
	RecordMenuToggle = {
		SetCallback = function(Callback: (Player: Player, Open: (boolean)) -> ()): () -> ()
			reliable_events[3] = Callback
			return function()
				reliable_events[3] = nil
			end
		end,
	},
	GetCloudConfig = {
		SetCallback = function(Callback: (Player: Player) -> ((({
			["latestVersion"]: (string),
			["featuredItems"]: ({ ({
				["itemId"]: (string),
				["itemType"]: ("Asset" | "Bundle"),
				["tintColor"]: ((string)?),
			}) }),
			["pinnedItems"]: ({ ({
				["itemId"]: (string),
				["itemType"]: ("Asset" | "Bundle"),
				["tintColor"]: ((string)?),
			}) }),
			["promotedItems"]: ({ ({
				["itemId"]: (string),
				["itemType"]: ("Asset" | "Bundle"),
				["tintColor"]: ((string)?),
				["promotionId"]: (string),
				["bid"]: (number),
				["startTime"]: (number),
				["endTime"]: (number),
			}) }),
			["cosmeticItems"]: ({ ({
				["itemId"]: (string),
				["itemType"]: ("Asset" | "Bundle"),
				["tintColor"]: ((string)?),
			}) }),
		})?))): () -> ()
			reliable_events[4] = Callback
			return function()
				reliable_events[4] = nil
			end
		end,
	},
	CloudConfigReset = {
		Fire = function(Player: Player)
			load_player(Player)
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			player_map[Player] = save()
		end,
		FireAll = function()
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireExcept = function(Except: Player)
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in Players:GetPlayers() do
				if player ~= Except then
					load_player(player)
					alloc(used)
					buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
					table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
					player_map[player] = save()
				end
			end
		end,
		FireList = function(List: { [unknown]: Player })
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for _, player in List do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
		FireSet = function(Set: { [Player]: any })
			load_empty()
			alloc(1)
			buffer.writeu8(outgoing_buff, outgoing_apos, 0)
			local buff, used, inst = outgoing_buff, outgoing_used, outgoing_inst
			for player in Set do
				load_player(player)
				alloc(used)
				buffer.copy(outgoing_buff, outgoing_apos, buff, 0, used)
				table.move(inst, 1, #inst, #outgoing_inst + 1, outgoing_inst)
				player_map[player] = save()
			end
		end,
	},
	BulkPurchaseAvatarItems = {
		SetCallback = function(Callback: (Player: Player, Value: ({ ({
			["Id"]: (string),
			["Type"]: ({
				["EnumType"]: (string),
				["Value"]: (number),
			}),
		}) })) -> ()): () -> ()
			reliable_events[0] = Callback
			return function()
				reliable_events[0] = nil
			end
		end,
	},
}
type Events = typeof(returns)
return returns
