--!strict
local Object = require(script.Object)
local Instance = require(script.Instance)
local BasePart = require(script.BasePart)
local DataModel = require(script.DataModel)
local GuiObject = require(script.GuiObject)
local GuiButton = require(script.GuiButton)

return {
	Object = Object,
	Instance = Instance,
	BasePart = BasePart,
	DataModel = DataModel,
	GuiObject = GuiObject,
	GuiButton = GuiButton,
}
